"""
FOUR-CORNER CALIBRATION  (bilinear interpolation)

You calibrate 4 points instead of 64. Everything else is computed.

  1. Run this script.
  2. It asks for a1, h1, a8, h8 in turn.
  3. Move the arm by hand so the CLAW SITS EXACTLY WHERE IT WOULD GRIP
     A PIECE ON THE CENTRE OF THAT SQUARE, then press SPACEBAR.
  4. It writes a fresh board_config.py with all 64 squares.

Take your time on those four. Every other square is derived from them,
so a 1 mm error in a corner is a 1 mm error everywhere.

Press ESC at any point to abort without writing anything.
USAGE
    python calibrate_corners.py           capture 4 corners, write board_config.py
    python calibrate_corners.py verify    hover over all 64 squares to check it
"""

import sys
import time
import math
import msvcrt
from pydobot import Dobot

PORT        = "COM4"                # Dobot Magician
CONFIG_FILE = "board_config.py"
HOVER       = 30.0                  # mm above each square, for the verify pass

FILES  = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
RANKS  = ['1', '2', '3', '4', '5', '6', '7', '8']
PIECES = ['p', 'r', 'n', 'b', 'q', 'k']

CORNERS = ["a1", "h1", "a8", "h8"]


def capture_point(device, label):
    """Block until SPACEBAR, then return the arm's current (x, y, z)."""
    print(f"\n==> Place the claw on the CENTRE of [{label.upper()}]"
          f" and press [SPACEBAR]   (ESC to abort)", end="", flush=True)
    while True:
        if msvcrt.kbhit():
            key = msvcrt.getch()
            if key == b'\x1b':                       # ESC
                print("\n\nAborted. board_config.py untouched.")
                device.close()
                sys.exit()
            if key == b' ':                          # SPACEBAR
                x, y, z = device.pose()[:3]
                print(f"\n    captured {label.upper()}: "
                      f"X={x:.1f}  Y={y:.1f}  Z={z:.1f}")
                time.sleep(0.4)                      # anti-bounce
                return (x, y, z)
        time.sleep(0.02)


def bilinear(c, u, v):
    """
    c = {'a1':(x,y,z), 'h1':..., 'a8':..., 'h8':...}
    u = 0..1 across files (a -> h)
    v = 0..1 across ranks (1 -> 8)
    """
    out = []
    for i in range(3):                               # x, y, z independently
        val = ((1 - u) * (1 - v) * c["a1"][i] +
               (    u) * (1 - v) * c["h1"][i] +
               (1 - u) * (    v) * c["a8"][i] +
               (    u) * (    v) * c["h8"][i])
        out.append(val)
    return out


def write_config(corners):
    lines = []
    lines.append("# " + "=" * 71)
    lines.append("#   CHESSBOARD COORDINATE MAP  -  generated by calibrate_corners.py")
    lines.append("# " + "=" * 71)
    lines.append("#   Built by bilinear interpolation from four measured corners:")
    for name in CORNERS:
        x, y, z = corners[name]
        lines.append(f"#     {name} = ({x:.1f}, {y:.1f}, {z:.1f})")
    lines.append("#")
    lines.append("#   All six piece types share a square's coordinates.")
    lines.append("#   Piece keys: 'p' 'r' 'n' 'b' 'q' 'k'")
    lines.append("")
    lines.append("SQUARE_MAP = {")

    for r_idx, rank in enumerate(RANKS):
        v = r_idx / 7.0
        lines.append(f"\n    # ---------------- RANK {rank} ----------------")
        for f_idx, file in enumerate(FILES):
            u = f_idx / 7.0
            x, y, z = bilinear(corners, u, v)
            square = f"{file}{rank}"
            lines.append(f'    "{square}": {{')
            for p in PIECES:
                lines.append(f'        "{p}": {{"x": {x:.1f}, "y": {y:.1f}, "z": {z:.1f}}},')
            lines.append("    },")

    lines.append("}")
    lines.append("")

    with open(CONFIG_FILE, "w") as f:
        f.write("\n".join(lines))


def verify(device):
    """Hover over every square so you can SEE whether the map is straight."""
    import board_config
    print("\nHovering 30 mm over each square. Watch the claw: it should sit dead")
    print("centre. If it drifts as it goes, a corner was off. Ctrl+C to stop.\n")
    for rank in RANKS:
        for file in FILES:
            sq = f"{file}{rank}"
            c = board_config.SQUARE_MAP[sq]["p"]
            print(f"  {sq}", end="  ", flush=True)
            device.move_to(c["x"], c["y"], c["z"] + HOVER, 0, wait=True)
            time.sleep(0.6)
        print()
    print("\nDone.")


# ---------------- MAIN ----------------
print(f"Connecting to Dobot on {PORT}...")
try:
    device = Dobot(port=PORT, verbose=False)
except Exception as e:
    print(f"[ERROR] Could not connect: {e}")
    sys.exit()

print("Connected.")
device.speed(100, 100)

if len(sys.argv) > 1 and sys.argv[1] == "verify":
    verify(device)
    device.close()
    sys.exit()

print("\n[!] Hold the unlock button on the arm head to move it freely.")

print("\n" + "=" * 62)
print("  FOUR-CORNER CALIBRATION")
print("  Corners, in order: a1, h1, a8, h8")
print("  SPACEBAR = capture   |   ESC = abort")
print("=" * 62)

corners = {}
for name in CORNERS:
    corners[name] = capture_point(device, name)

# --- sanity check: opposite corners should be roughly equal distances apart ---
def dist(p, q):
    return math.dist(p[:2], q[:2])

w1 = dist(corners["a1"], corners["h1"])      # rank-1 edge
w2 = dist(corners["a8"], corners["h8"])      # rank-8 edge
h1_ = dist(corners["a1"], corners["a8"])     # a-file edge
h2 = dist(corners["h1"], corners["h8"])      # h-file edge

print("\n--- board geometry check ---")
print(f"  rank1 edge a1-h1: {w1:.1f} mm")
print(f"  rank8 edge a8-h8: {w2:.1f} mm   (diff {abs(w1-w2):.1f} mm)")
print(f"  a-file  a1-a8:    {h1_:.1f} mm")
print(f"  h-file  h1-h8:    {h2:.1f} mm   (diff {abs(h1_-h2):.1f} mm)")

if abs(w1 - w2) > 5 or abs(h1_ - h2) > 5:
    print("\n  [!] Opposite edges differ by more than 5 mm.")
    print("      Either a corner is off, or the board isn't square to the arm.")
    ans = input("      Write the file anyway? (y/n): ").strip().lower()
    if ans != "y":
        print("Aborted. board_config.py untouched.")
        device.close()
        sys.exit()

write_config(corners)
print(f"\n[Done] Wrote all 64 squares to {CONFIG_FILE}.")
print("       Next: run test_pawns.py and check e2 -> e4 before playing.")

device.close()